# Generated by Django 3.0.5 on 2021-05-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, unique=True)),
                ('page_number', models.PositiveIntegerField()),
                ('page', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
